### PR TITLE
Updated BayesNets

### PR DESCRIPTION
**Pull request by smkatz12**
Fixed a few errors that were noted in the BayesNet structures. Updated the documentation and examples accordingly.

### CODE REVIEW

**Comment by rguendel-MIT** [comment]
It appears that the changes are primarily in binary files? Can you say anything about the nature of the changes?

**Comment by smkatz12** [comment]
> It appears that the changes are primarily in binary files? Can you say anything about the nature of the changes?

Sure, a researcher at NASA Ames was sampling from the networks and noticed a couple discrepancies between the networks and Eric's original 2016 paper. Specifically, rrHeaddot and rrHeaddot_tp1 were missing a bin in the CPDs, and one of the dependencies in the transition Bayes net was flipped from the diagram in the paper.

I originally did not have access to Eric's Bayes nets and had relearned all the parameters. I ended up getting access to his original networks, so I converted his networks to work with BayesNets.jl and replaced the old ones with is original networks. The researcher at NASA confirmed that this seems to fix the issues. I placed the old networks in a folder called old_networks for reference.

**Comment by aweinert-MIT** [comment]
> > It appears that the changes are primarily in binary files? Can you say anything about the nature of the changes?
> 
> Sure, a researcher at NASA Ames was sampling from the networks and noticed a couple discrepancies between the networks and Eric's original 2016 paper. Specifically, rrHeaddot and rrHeaddot_tp1 were missing a bin in the CPDs, and one of the dependencies in the transition Bayes net was flipped from the diagram in the paper.
> 
> I originally did not have access to Eric's Bayes nets and had relearned all the parameters. I ended up getting access to his original networks, so I converted his networks to work with BayesNets.jl and replaced the old ones with is original networks. The researcher at NASA confirmed that this seems to fix the issues. I placed the old networks in a folder called old_networks for reference.

Can you please add a README to the `old_networks` directory and provide a similar explanation? Can you also add a README to the `examples` directory with a brief description? It is unclear to me if the example is from the 2016 original paper or something more recent.

**Comment by smkatz12** [comment]
> > > It appears that the changes are primarily in binary files? Can you say anything about the nature of the changes?
> > 
> > 
> > Sure, a researcher at NASA Ames was sampling from the networks and noticed a couple discrepancies between the networks and Eric's original 2016 paper. Specifically, rrHeaddot and rrHeaddot_tp1 were missing a bin in the CPDs, and one of the dependencies in the transition Bayes net was flipped from the diagram in the paper.
> > I originally did not have access to Eric's Bayes nets and had relearned all the parameters. I ended up getting access to his original networks, so I converted his networks to work with BayesNets.jl and replaced the old ones with is original networks. The researcher at NASA confirmed that this seems to fix the issues. I placed the old networks in a folder called old_networks for reference.
> 
> Can you please add a README to the `old_networks` directory and provide a similar explanation? Can you also add a README to the `examples` directory with a brief description? It is unclear to me if the example is from the 2016 original paper or something more recent.

Added!

**Review by aweinert-MIT — APPROVED** [review]
This looks good. I did not test the Julia code. However the software changes are minimal and I trust @smkatz12. 

@rguendel-MIT, we should add at least a SPDX file to the root directory but we can handle that in a different pull request.

**Pull request merged**
